services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: www-data
                uid: 1000
        container_name: laravel-app
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: support_payment
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_USER: laravel
            MYSQL_PASSWORD: 123456789
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: 123456789
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge