services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - REVERB_HOST=reverb
            - REVERB_PORT=8080
            - REVERB_SCHEME=http
            - REVERB_APP_KEY=5ewfgfgvsax8funcd7hl
            - REVERB_APP_SECRET=wtwqsxvwqi4bsqgtczcp
            - REVERB_APP_ID=774135
        depends_on:
            - mysql
        networks:
            - laravel-network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    reverb:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_reverb
        command: php artisan reverb:start --host=0.0.0.0 --port=8080
        volumes:
            - .:/var/www/html
        ports:
            - "8080:8080"
        depends_on:
            - app
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root_secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
