services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support-payment-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_HOST=db
      - DB_DATABASE=support_payment
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - MEMCACHED_HOST=memcached
      - CACHE_DRIVER=memcached
      - SESSION_DRIVER=memcached
      - QUEUE_DRIVER=database
      - Pusher_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_SCHEME=${PUSHER_SCHEME}
      - PUSHER_PORT=${PUSHER_PORT}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
      - REVERB_APP_SECRET=${REVERB_APP_SECRET}
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_HOST=${REVERB_HOST}
      - REVERB_SCHEME=${REVERB_SCHEME}
      - REVERB_PORT=${REVERB_PORT}
    networks:
      - support-payment-network

  db:
    image: mysql:8.0
    container_name: support-payment-db
    restart: unless-stopped
    volumes:
      - support-payment-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=support_payment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - support-payment-network

  nginx:
    image: nginx:alpine
    container_name: support-payment-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - support-payment-network

  memcached:
    image: memcached:latest
    container_name: support-payment-memcached
    restart: unless-stopped
    networks:
      - support-payment-network

networks:
  support-payment-network:
    driver: bridge

volumes:
  support-payment-db:
